### ISSUE TITLE
Contato

### ISSUE THREAD

**Issue by Saulo1501** [SamuellH12/Competitive-Programming-Algorithms#1]
Olá você da aulas de programação competitiva?

**Comment by SamuellH12** [comment]
De vez em quando abro algum grupo pra aulas de programação competitiva, mas é bem aleatório, não tem um padrão de datas ou formato bem definido. Mas tem algumas aulas gravadas que eu posto no youtube e ocasionalmente posso mandar mais algum material por lá.
Se quiser dar uma olhada tá aqui: https://www.youtube.com/@samuellh12

**Comment by Saulo1501** [comment]
Eu entrei em contato justamente por causa das aulas que vi no YouTube, mas
tem muitos exercícios que eu não consigo resolver. Gostaria de saber se
você está dando aulas particulares, e se não estiver, pode entrar em
contato comigo quando abrir as aulas novamente? As aulas seriam para a
prova da obi no fim de setembro, nível 1 fase 3.

Em dom., 1 de set. de 2024, 17:31, Samuell H ***@***.***>
escreveu:
